# Header
menu:                      # Links in the navigation bar
  Home: /
  Archives: /archives
  About: /about
rss: /atom.xml

home:
  style: default           # default, detail

favicon: /img/favicon.png        # Path to the custom favicon relative to /source (e.g. "/favicon.png" if your favicon file is located at /source/favicon.png)

# Banner
banner: 
  enable: true                  # Display banner
  url: /img/banner.jpg                          # Path to the banner image relative to /source. Web url is also supported
  position: center               # Specifies the alignment of the image, see the "object-position" property in CSS
  onAllPages: true               # Display banner on all pages instead of only the home page

# Appearance
hue: 240                          # The hue of the theme color (e.g. red: 0, orange: 60, blue: 260, purple: 300, pink: 345)
                                 # Visit `saicaca.github.io/vivia-preview` to preview the theme color

# Personal info
avatar: /img/avatar.png             # Path to the avatar image relative to /source
author: lyc、wj
subtitle: '终点未至，脚步未停'
links:
  - name: Bilibili
    icon: fa-brands fa-bilibili      # Find icon codes at https://fontawesome.com/search
    url: https://bilibili.com
  - name: GitHub
    icon: fa-brands fa-github
    url: https://github.com/lyc-28

# Sidebar
sidebar:
  widgets:                 # Plugins to be enabled (profile, category, tag, archive, recent_posts)
    normal:                # Scroll along with the page
      - profile
    sticky:                # Stick to the top of the page
      - category
      - tag
#      - archive
#      - recent_posts

# Sidebar Widget behavior
archive_type: 'monthly'
recent_posts_limits: 5
categories:
  max_depth: 2             # Maximum depth of categories displayed in the widget (null for unlimited)

# Third-party comment system
comment:
  valine:
    enable: false         # Enable Valine comment system
    appId: 
    appKey: 
    placeholder: 
    pageSize: 10
    highlight: true
    serverURLs: 
    requiredFields: 
    # Other supported parameters can be added here if needed
    # Visit https://valine.js.org/configuration.html for more details
  twikoo:
    enable: false          # Enable Twikoo comment system
    envID: 
    region:
    path: location.pathname
    lang:
    # See also: https://github.com/imaegoo/twikoo
  waline:
    enable: true
    serverURL: https://lblog.zeabur.app/  # <--- 填你刚才在 Zeabur 生成的网址
    placeholder: 请随便说两句（无需登录）...      # 提示语
    avatar: robohash                           # 头像风格
    pageSize: 10
    visitor: true                              # 统计阅读量
    requiredMeta: ['nick']                     # 必填项：只填昵称即可
    # requiredMeta: ['nick', 'mail']           # 如果你想让邮箱也必填就用这一行

#Analytics
gauges_analytics: false
google_analytics: false #UA-xxxxxx
baidu_analytics: false # ddxxxxxxxxxxxxxxxxx In the https://hm.baidu.com/hm.js? Afterwards
